[project]
name = "echo-chamber"
version = "0.1.0"
description = "A simple Flask API for CI/CD learning."
dependencies = [
    "flask>=3.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
]